info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

server:
  port: 8888

security:
  user:
    name: admin
    password: admin123

eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: ${spring.application.name}

spring:
    application:
      name: admin
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: w123456
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    freemarker:
          allow-request-override: false
          allow-session-override: false
          cache: false
          charset: UTF-8
          check-template-location: true
          content-type: text/html
          enabled: true
          expose-request-attributes: false
          expose-session-attributes: false
          expose-spring-macro-helpers: true
          prefer-file-system-access: true
          suffix: .ftl
          template-loader-path: ["classpath:/templates/"]
          settings:
            # template_update_delay : 1
            default_encoding : UTF-8
            number_format : 0.##########
            datetime_format : yyyy-MM-dd HH:mm:ss
            classic_compatible : true
            locale : zh_CN
    resources:
          static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

logging:
    path: logs

mybatis:
    mapperLocations: classpath:mapper/**/**.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql