info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

server:
  port: 3333

security:
  user:
    name: admin
    password: admin123

eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@192.168.100.194:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: ${spring.application.name}

spring:
    application:
      name: face-api
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

logging:
    path: logs

